#
# Github pages customized 
# for redroundrobin.site
#

theme: minima
title: "Red Round Robin"
description: >
  Sito ufficiale per il progetto di Ingegneria del software, gruppo 6, Universit√† di Padova

author: Red Round Robin Corporation
email: info@redroundrobin.site
# remote_theme: jekyll/minima@v2.5.0
show_excerpts: false


minima: 
  date_format: "%d %B %Y"
  social_links: 
    github: maxelweb

header_pages: 
  - membri.md
  - contatti.md
